# snap/snapcraft.yaml

name: clip-transfer
base: core22
version: '1.0.0'
summary: Seamless LAN clipboard/text transfer app
description: |
  ClipTransfer is a lightweight cross-platform tool for sharing text and clipboard content across devices on the same local network.

grade: stable
confinement: strict

apps:
  clip-transfer:
    command: bin/clip-transfer
    desktop: usr/share/applications/clip-transfer.desktop
    plugs:
      - network
      - x11
      - wayland
      - desktop
      - desktop-legacy

parts:
  clip-transfer:
    plugin: make
    source: .
    build-packages:
      - gcc
      - make
      - cmake
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      # Copier le binaire compilé — ajuster ce chemin si besoin
      install -Dm755 clip-transfer $SNAPCRAFT_PART_INSTALL/bin/clip-transfer

      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/applications
      install -Dm644 res/clip-transfer.desktop $SNAPCRAFT_PART_INSTALL/usr/share/applications/clip-transfer.desktop

      for size in 16 32 64 128 256 512 1024; do
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/${size}x${size}/apps
        install -Dm644 res/logo_${size}x${size}.png $SNAPCRAFT_PART_INSTALL/usr/share/icons/hicolor/${size}x${size}/apps/clip-transfer.png
      done
