name: C++ Make and Cmake

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake make git g++ \
          qt6-base-dev qt6-base-dev-tools \
          qt6-tools-dev qt6-tools-dev-tools
        
    - name: Build with Make
      run: |
        make re_release
