Param(
  [ValidateSet('Release','Debug')]
  [string]$Config = 'Release',
  [string]$BuildDir = "${PSScriptRoot}\..\build",
  [string]$OutDir = "${PSScriptRoot}\..\dist\windows\deploy",
  [string]$QtBinDir = $env:QT_BIN_DIR
)

$ErrorActionPreference = 'Stop'

function Assert-Path([string]$Path, [string]$Hint) {
  if (-not (Test-Path $Path)) {
    throw "Chemin introuvable: $Path. $Hint"
  }
}

# Build
Push-Location (Resolve-Path "${PSScriptRoot}\..")
try {
  cmake --build $BuildDir --config $Config

  # Find exe (this repo currently links to project-root ClipTransfer.exe)
  $exeCandidates = @(
    (Join-Path (Get-Location) 'ClipTransfer.exe'),
    (Join-Path $BuildDir 'ClipTransfer.exe'),
    (Join-Path (Join-Path $BuildDir $Config) 'ClipTransfer.exe')
  )

  $exePath = $exeCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
  if (-not $exePath) {
    throw "Impossible de trouver ClipTransfer.exe (cherché: $($exeCandidates -join ', '))"
  }

  # Prepare output
  New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
  Copy-Item -Force $exePath (Join-Path $OutDir 'ClipTransfer.exe')

  # Copy translations next to exe (generated by CMake under build/)
  $i18nSrcCandidates = @(
    (Join-Path $BuildDir 'i18n'),
    (Join-Path (Get-Location) 'i18n')
  )
  $i18nSrc = $i18nSrcCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
  if ($i18nSrc) {
    New-Item -ItemType Directory -Force -Path (Join-Path $OutDir 'i18n') | Out-Null
    Copy-Item -Recurse -Force (Join-Path $i18nSrc '*') (Join-Path $OutDir 'i18n')
  }

  # Deploy Qt runtime
  if (-not $QtBinDir) {
    # MSYS2 MinGW64 default
    $msys2Mingw64 = 'C:\msys64\mingw64\bin'
    if (Test-Path (Join-Path $msys2Mingw64 'windeployqt-qt6.exe')) {
      $QtBinDir = $msys2Mingw64
      Write-Host "QT_BIN_DIR non défini: MSYS2 détecté ($QtBinDir)"
    } else {
      Write-Host "QT_BIN_DIR non défini: tentative via PATH (windeployqt-qt6.exe / windeployqt.exe)"
    }
  }

  if (-not $QtBinDir) {
    $windeployqtCmd = (Get-Command windeployqt-qt6.exe -ErrorAction SilentlyContinue)
    if (-not $windeployqtCmd) {
      $windeployqtCmd = (Get-Command windeployqt.exe -ErrorAction SilentlyContinue)
    }
    if ($windeployqtCmd) { $windeployqt = $windeployqtCmd.Source }
  } else {
    $candidates = @(
      (Join-Path $QtBinDir 'windeployqt-qt6.exe'),
      (Join-Path $QtBinDir 'windeployqt.exe')
    )
    $windeployqt = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
  }

  if (-not $windeployqt) {
    throw "windeployqt introuvable. Pour MSYS2 MINGW64, mets QT_BIN_DIR=C:\\msys64\\mingw64\\bin ou ajoute windeployqt-qt6.exe au PATH."
  }
  Assert-Path $windeployqt "Installe Qt et assure-toi que windeployqt est disponible."

  # --compiler-runtime est crucial pour les builds MSYS2/MinGW:
  # ça copie libstdc++/libgcc/libwinpthread à côté de l'exe.
  $deployArgs = @(
    '--no-translations',
    '--no-system-d3d-compiler',
    '--compiler-runtime'
  )
  if ($Config -eq 'Debug') { $deployArgs += '--debug' } else { $deployArgs += '--release' }
  $deployArgs += (Join-Path $OutDir 'ClipTransfer.exe')
  & $windeployqt @deployArgs

  Write-Host "OK: bundle prêt dans $OutDir"
  Write-Host "Ensuite, pour construire l'installateur: ISCC.exe installer\ClipTransfer.iss"
}
finally {
  Pop-Location
}
